export type Tool = {
  name: string;
  category: string;
  description: string;
  bestFor: string;
  pricing: string;
  href: string;
  featured?: boolean;
};

export const tools: Tool[] = [
  // ── Crypto Exchanges (affiliate priority) ──────────────────────────────
  {
    name: "Coinbase",
    category: "Crypto Exchange",
    description: "One of the most beginner-friendly crypto exchanges available in the UK. Regulated, simple to use, and supports GBP deposits via bank transfer.",
    bestFor: "UK beginners buying Bitcoin and Ethereum",
    pricing: "Fee per trade (varies by method)",
    href: "https://www.coinbase.com/join/jrobertson_1A8sYA",
    featured: true,
  },
  {
    name: "Kraken",
    category: "Crypto Exchange",
    description: "Low-fee exchange with strong security, UK bank support, staking, and advanced trading features. One of the most trusted names in crypto.",
    bestFor: "Intermediate UK traders and stakers",
    pricing: "Maker/taker fees from 0.16%",
    href: "https://kraken.app.link/PzxrgWP7Qzb",
    featured: true,
  },
  {
    name: "Binance",
    category: "Crypto Exchange",
    description: "The world's largest crypto exchange by volume. Huge range of coins, low fees, and advanced tools. Check current FCA registration status before use.",
    bestFor: "Experienced traders seeking low fees and coin variety",
    pricing: "0.1% standard fee (discount with BNB)",
    href: "https://www.binance.com/en/activity/referral-entry/CPA?ref=CPA_00JDHMDHBA",
  },
  {
    name: "Bybit",
    category: "Crypto Exchange",
    description: "Popular derivatives and spot exchange with competitive fees, a wide range of tokens, and a growing UK user base.",
    bestFor: "Traders interested in futures and spot markets",
    pricing: "0.1% spot fee",
    href: "https://www.bybit.com/invite?ref=2WKAA",
  },
  // ── Hardware Wallets (affiliate priority) ──────────────────────────────
  {
    name: "Ledger",
    category: "Hardware Wallet",
    description: "Market-leading cold storage hardware wallet. Keeps your private keys offline and supports 5,500+ coins. Essential for anyone holding significant crypto.",
    bestFor: "Self-custody and long-term storage",
    pricing: "From £59 (Nano S Plus)",
    href: "https://shop.ledger.com/?referral_code=FN50B8J0VZNVR",
    featured: true,
  },
  {
    name: "Trezor",
    category: "Hardware Wallet",
    description: "Open-source hardware wallet with a long security track record. Transparent firmware, strong community, and no-frills secure storage.",
    bestFor: "Privacy-focused crypto holders",
    pricing: "From £49 (Model One)",
    href: "https://trezor.io/",
  },
  // ── Crypto Tax Tools (affiliate priority) ──────────────────────────────
  {
    name: "Koinly",
    category: "Crypto Tax",
    description: "The most popular crypto tax tool for UK users. Connects to 700+ exchanges and wallets, calculates your HMRC capital gains automatically.",
    bestFor: "UK crypto investors who need tax reports",
    pricing: "Free plan; paid from £49/year",
    href: "https://koinly.io/?via=digitechlifestyle",
    featured: true,
  },
  // ── AI Writing Tools (affiliate priority) ──────────────────────────────
  {
    name: "Writesonic",
    category: "AI Writing",
    description: "AI writing platform for blog posts, SEO articles, ad copy, and product descriptions. Includes an AI article writer and SEO optimiser.",
    bestFor: "Content creators and affiliate marketers",
    pricing: "Free trial; paid from $19/month",
    href: "https://writesonic.com/",
  },
  // ── Hosting (affiliate priority) ───────────────────────────────────────
  {
    name: "Hostinger",
    category: "Web Hosting",
    description: "Affordable web hosting with WordPress one-click install, free domain, and SSL. Popular choice for beginners building their first site in the UK.",
    bestFor: "Beginners starting a blog or website",
    pricing: "From £2.99/month (promotional pricing)",
    href: "https://www.hostinger.com/",
  },
  // ── AI Tools (general) ─────────────────────────────────────────────────
  {
    name: "ChatGPT",
    category: "AI Assistant",
    description: "Research, drafting, workflow planning, code help, and business ideation in one general-purpose assistant.",
    bestFor: "Solo operators and small teams",
    pricing: "Free and paid plans",
    href: "https://chat.openai.com",
    featured: true,
  },
  {
    name: "Notion AI",
    category: "Workspace AI",
    description: "Docs, wikis, project notes, and AI summaries for content and operations teams.",
    bestFor: "Knowledge management",
    pricing: "Paid add-on",
    href: "https://www.notion.so",
    featured: true,
  },
  {
    name: "Zapier",
    category: "Automation",
    description: "Connect thousands of apps and automate repetitive marketing, sales, and admin tasks.",
    bestFor: "No-code app workflows",
    pricing: "Free and paid plans",
    href: "https://zapier.com",
    featured: true,
  },
  {
    name: "Make",
    category: "Automation",
    description: "Visual automation builder for multi-step business processes and data routing.",
    bestFor: "Advanced no-code automations",
    pricing: "Free and paid plans",
    href: "https://www.make.com",
  },
  {
    name: "ConvertKit",
    category: "Newsletter",
    description: "Email capture, automations, landing pages, and creator commerce for newsletter-led businesses.",
    bestFor: "Creators and affiliates",
    pricing: "Free and paid plans",
    href: "/newsletter",
  },
  {
    name: "Ledger",
    category: "Crypto Wallet",
    description: "Hardware wallet storage for people who want more control over long-term digital assets.",
    bestFor: "Self-custody",
    pricing: "Paid device",
    href: "/blog/best-crypto-wallets-uk-2025",
  },
  {
    name: "Grammarly",
    category: "AI Writing",
    description: "Writing quality checks, tone adjustments, and grammar support for everyday publishing.",
    bestFor: "Content production",
    pricing: "Free and paid plans",
    href: "https://www.grammarly.com",
  },
  {
    name: "Canva",
    category: "Creator Tools",
    description: "Fast design, brand kits, short-form creative assets, and AI-assisted visual production.",
    bestFor: "Content creators",
    pricing: "Free and paid plans",
    href: "https://www.canva.com",
  },
  {
    name: "DeepSeek",
    category: "AI Assistant",
    description: "High-performance AI reasoning and chat from China's DeepSeek lab — competitive with GPT-4 class models at a fraction of the cost.",
    bestFor: "Cost-effective AI reasoning",
    pricing: "Free and paid plans",
    href: "https://www.deepseek.com/en/",
    featured: true,
  },
  {
    name: "Apple Container",
    category: "Developer Tools",
    description: "Run Linux containers as lightweight VMs on a Mac. Written in Swift, optimised for Apple Silicon — no Docker daemon needed.",
    bestFor: "Mac developers using containers",
    pricing: "Free, open source",
    href: "/blog/apple-container-review-2026",
  },
  {
    name: "Tolaria",
    category: "AI Productivity",
    description: "Desktop app for macOS, Windows, and Linux that manages markdown knowledge bases — notes, docs, and wikis in one local workspace.",
    bestFor: "Knowledge management",
    pricing: "Free, open source",
    href: "/blog/tolaria-review-2026",
  },
  {
    name: "LMCache",
    category: "AI Infrastructure",
    description: "Supercharge LLM inference with a persistent KV cache layer — cuts time-to-first-token and improves throughput for long-context workloads.",
    bestFor: "LLM developers and AI engineers",
    pricing: "Free, open source",
    href: "/blog/lmcache-review-2026",
  },
  {
    name: "Microsoft PowerToys",
    category: "Developer Tools",
    description: "Power-user utilities for Windows — FancyZones window management, colour picker, file renaming, spotlight search, and 20+ more tools.",
    bestFor: "Windows power users",
    pricing: "Free, open source",
    href: "/blog/microsoft-powertoys-review-2026",
  },
  {
    name: "Taste Skill",
    category: "AI Coding",
    description: "Portable Claude Code skill that gives AI coding agents better design taste — stops generic slop layouts and enforces premium typography and spacing.",
    bestFor: "Developers using AI coding agents",
    pricing: "Free, open source",
    href: "/blog/taste-skill-review-2026",
  },
  {
    name: "OpenCV",
    category: "AI & Vision",
    description: "The world's most popular open-source computer vision library — 2,500+ algorithms for image processing, object detection, and video analysis.",
    bestFor: "Computer vision developers",
    pricing: "Free, open source",
    href: "/blog/opencv-review-2026",
  },
  {
    name: "Academic Research Skills",
    category: "AI Coding",
    description: "Claude Code skills suite for the full academic research pipeline — research, write, review, revise, and finalise papers with AI assistance.",
    bestFor: "Researchers and PhD students",
    pricing: "Free, open source",
    href: "/blog/academic-research-skills-claude-code-review-2026",
  },
  {
    name: "CloakBrowser",
    category: "Privacy Tools",
    description: "Stealth Chromium browser with source-level fingerprint patches — passes Cloudflare, FingerprintJS, and BrowserScan. Drop-in Playwright replacement.",
    bestFor: "Privacy, multi-accounting, scraping",
    pricing: "Free tier, paid plans",
    href: "/blog/cloakbrowser-review-2026",
  },
  {
    name: "Hermes Desktop",
    category: "AI Productivity",
    description: "Native desktop app for installing and managing Hermes Agent — a self-improving AI assistant with tool use, memory, skills, and multi-platform messaging.",
    bestFor: "AI power users",
    pricing: "Free, open source",
    href: "/blog/hermes-desktop-review-2026",
  },
  {
    name: "FxEmbed",
    category: "Social Media Tools",
    description: "Fix broken X/Twitter and Bluesky embeds on Discord and Telegram — adds multiple images, polls, video, and translations to shared links.",
    bestFor: "Discord and Telegram communities",
    pricing: "Free, open source",
    href: "/blog/fxembed-review-2026",
  },
  {
    name: "GentleOS/16",
    category: "Developer Tools",
    description: "Hobby operating system for vintage 16-bit PCs. A minimalist, educational OS built from scratch — great for learning low-level systems programming.",
    bestFor: "OS development learners",
    pricing: "Free, open source",
    href: "/blog/gentleos-review-2026",
  },
  {
    name: "cua (trycua)",
    category: "AI Infrastructure",
    description: "Open-source infrastructure for computer-use AI agents — sandboxes, SDKs, and benchmarks for agents that control full desktops (macOS, Linux, Windows).",
    bestFor: "AI agent developers",
    pricing: "Free, open source",
    href: "/blog/cua-trycua-review-2026",
  },
  {
    name: "Superlog",
    category: "AI Infrastructure",
    description: "Open-source observability tool that uses AI agents to self-heal your software — ingests traces, logs, and metrics and groups noisy signals into incidents.",
    bestFor: "Dev teams and SREs",
    pricing: "Free, open source",
    href: "/blog/superlog-review-2026",
  },
  {
    name: "Intelligent Terminal",
    category: "Developer Tools",
    description: "Microsoft's fork of Windows Terminal with native AI agent integration — Claude Code, Copilot, Codex, and Gemini CLI right in your command line.",
    bestFor: "Windows developers using AI agents",
    pricing: "Free, open source",
    href: "/blog/microsoft-intelligent-terminal-review-2026",
  },
  {
    name: "AgentPet",
    category: "AI Productivity",
    description: "Native macOS menu bar app with a desktop pet that monitors your AI coding agents (Claude Code, Codex, Gemini CLI) in real time.",
    bestFor: "macOS developers running AI agents",
    pricing: "Free, open source",
    href: "/blog/agentpet-review-2026",
  },
  {
    name: "Canary",
    category: "AI Coding",
    description: "QA harness built for Claude Code — E2E testing with screen recordings, console logs, network HARs, and Playwright traces in one tool.",
    bestFor: "Teams using Claude Code",
    pricing: "Free, open source",
    href: "/blog/canary-qa-review-2026",
  },
  {
    name: "AlignDev",
    category: "AI Coding",
    description: "7-step wizard that generates shared coding standards and SKILL.md files so Claude Code, Codex, Cursor, and Copilot all write consistently.",
    bestFor: "Teams using multiple AI coding agents",
    pricing: "Free, open source",
    href: "/blog/aligndev-review-2026",
  },
  {
    name: "BrandDocs",
    category: "AI Productivity",
    description: "Agent skills that learn your existing Word, PowerPoint, and Excel templates and generate new on-brand documents preserving your styles and formulas.",
    bestFor: "Teams with strict brand guidelines",
    pricing: "Free, open source",
    href: "/blog/branddocs-review-2026",
  },
  {
    name: "Neo3dEngine",
    category: "Developer Tools",
    description: "Minimalist CPU-based 3D console engine in C# — raycasting, dynamic lighting, .obj loader, and TCP multiplayer. Zero external graphics APIs.",
    bestFor: "Game dev learners and hobbyists",
    pricing: "Free, open source",
    href: "/blog/neo-3d-engine-review-2026",
  },
];
